### PR TITLE
Disable Jetifier (fixes #726)

### LINKED ISSUE #726: Disable Jetifier
Ref.: https://github.com/syncthing/syncthing-android/pull/1561#issuecomment-731613918

Hello @Catfriend1,
Yes, I can help. I've just checked and for this project can-i-drop-jetifier outputs:
```
./gradlew -Pandroid.enableJetifier=false canIDropJetifier
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :app:canIDropJetifier
========================================
Project app
========================================

Cannot drop Jetifier due to following external dependencies:

* com.journeyapps:zxing-android-embedded:3.6.0
```

Upgrading `com.journeyapps:zxing-android-embedded` to the newest version (4.1.0) fails the build with the following error:

```./gradlew build                                          

> Task :app:processDebugManifest FAILED
/Users/ziem/Projects/syncthing-android-fork/app/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.journeyapps:zxing-android-embedded:4.1.0] /Users/ziem/.gradle/caches/transforms-2/files-2.1/8df16b5621651697bf618cdc3c51d973/jetified-zxing-android-embedded-4.1.0/AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.google.zxing.client.android" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

BUILD FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.journeyapps:zxing-android-embedded:4.1.0] /Users/ziem/.gradle/caches/transforms-2/files-2.1/8df16b5621651697bf618cdc3c51d973/jetified-zxing-android-embedded-4.1.0/AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.google.zxing.client.android" to force usage (may lead to runtime failures)

...
```

Setting `minSdkVersion` to `24` fails the build with the following error:

```
./gradlew build

...

> Task :app:lint FAILED
BUILD FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /Users/ziem/Projects/syncthing-android-fork/app/src/main/java/com/nutomic/syncthingandroid/views/WifiSsidPreference.java:181: Error: Missing permissions required by WifiManager.getConfiguredNetworks: android.permission.ACCESS_FINE_LOCATION [MissingPermission]
              configuredNetworks = wifiManager.getConfiguredNetworks();
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Applies to variants: gplay
  
...
```

Here I realized that my `main` branch was outdated. Updating it to 8496068a1fb57537677bb3f2bd782eabc06f55ff fixed this issue and now running `./gradlew build` outputs `BUILD SUCCESSFUL` when `android.enableJetifier=false` 🎉 

I can create a PR with all my changes. Let me know what do you think.

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
- Disable Jetifier (fixes #726)

Thanks to @ziem  for helping me with this 🍿  :-).

### CODE REVIEW

File: app/src/main/java/com/nutomic/syncthingandroid/activities/PhotoShootActivity.java [hunk 1]
```diff
@@ -171,10 +170,12 @@ private void openCameraIntent() {
         if (photoFile != null) {
             Uri photoURI = FileProvider.getUriForFile(this, getPackageName() + ".provider", photoFile);
             pictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
+            /*
             if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.LOLLIPOP) {
                 pictureIntent.setClipData(ClipData.newRawUri("", photoURI));
                 pictureIntent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
             }
+            */
```
Comment (ziem) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/PhotoShootActivity.java:178]: I think you can remove it completely since `minSdkVersion` is `24` now.

**Review by ziem — APPROVED** [review]
Everything looks good 👍 😉 

`zxing-android-embedded` requires `minSdkVersion 24` so there is not much you can do regarding this change.

**Comment by Catfriend1** [comment]
@ziem : I've compiled it and gave it a test shot on my AVD 10 VM. Now libSyncthingnative.so (the syncthing core) doesn't run anymore. I'm getting "ExecutableNotFound".

```
2020-11-22 14:10:56.365 10511-10623/com.github.catfriend1.syncthingandroid.debug E/SyncthingRunnable: CRITICAL - Syncthing core binary is missing in APK package location /data/app/com.github.catfriend1.syncthingandroid.debug-5ywadM5DkRHWmG-KssXGFA==/lib/x86/libsyncthingnative.so
2020-11-22 14:10:56.365 10511-10623/com.github.catfriend1.syncthingandroid.debug E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.github.catfriend1.syncthingandroid.debug, PID: 10511
    java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid.debug-5ywadM5DkRHWmG-KssXGFA==/lib/x86/libsyncthingnative.so
        at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
        at java.lang.Thread.run(Thread.java:919)
2020-11-22 14:10:56.365 10511-10623/com.github.catfriend1.syncthingandroid.debug E/SyncthingService: mSyncthingRunnableThread: Uncaught exception [ExecutableNotFoundException]
```

Do you have an idea why the executable extraction or execution fails now? Reverting this PR immediately brings it back to life again.

File: app/src/main/java/com/nutomic/syncthingandroid/activities/PhotoShootActivity.java (hunk 1 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/activities/PhotoShootActivity.java]: Ok, removed that commented part. :)

**Comment by Catfriend1** [comment]
@ziem : Reverting commits one by one until the first one ( 1ccb1a29cb5a17b8084085b4595ec7c3ba28713d ) makes the exec work again. I don't know why libSyncthingNative.so isn't executing any longer when minApi > 24 and zxing > 4.1.0 has happened.

**Comment by Catfriend1** [comment]
I've also some problems understanding why the offical syncthing-android can stay an minApi16 + zxing 3.6.0 with enableJetifier=false while the fork has a library conflict forcing to go up to API 24?!

**Comment by Catfriend1** [comment]
OK, it seems like Android changed something related to the native lib extraction, because anything higher than API 22 does result in ExecutableNotFound.

**Comment by ziem** [comment]
I've just checked and it is possible to update `zxing-android-embedded` without bumping `minSdkVersion`: https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions. Could you try it?

**Comment by Catfriend1** [comment]
Yes, the transitive = false makes it possible to disable jetifier and stay at minApi = 21. I feel like going to minApi = 24 later because we get the libsyncthingnative.so extraction restrictions then from Android causing more work to do. Sometime in the future, we'll have to do that, but now users would be happier - I guess - if Android 5.x is still supported.
